### ISSUE TITLE
Implement basic navigation through survey

### ISSUE THREAD

**Issue by cswaney** [princeton-ddss/safely-report#1]
# Description

Implement simple back-and-forth navigation through survey elements, with minimal UI

# Tasks

- [x] Set up Flask environment
- [x] Create XLSForm parser
- [x] Prototype survey navigator capable of simple linear travel between survey elements
- [x] Make minimal UI where the user can move back or forward between survey elements
- [x] Set up Python linter
