### ISSUE TITLE
Configure unit tests for survey processor

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#10]
# Description

Use mock and/or patch to configure unit testing for `SurveyProcessor`

# Tasks

- [x] Reorganize `tests/` folder to set up unit tests for `SurveyProcessor`
- [x] Test `SurveyProcessor.curr_lang` using mock and patch
- [x] Test `SurveyProcessor.get_value()`
- [x] Test `SurveyProcessor.set_curr_value()`
