### ISSUE TITLE
Clean up code in `build-survey-processing-engine` branch

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#11]
# Description

Clean up code in `build-survey-processing-engine` to make it ready for the first (big) PR review.

# Tasks

- [x] Reduce redundant operations inside each method of `SurveyProcessor`
- [x] Use class name to call static methods
- [x] Evaluate any XLSForm variables in the extracted text
- [x] Add example XLSForm from https://stats4sd.org for testing
