### ISSUE TITLE
Configure integration tests for survey processor

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#12]
# Description

For more effective testing, we will:

- Prioritize writing unit tests for public methods
- Use integration tests to examine the overall behavior of `SurveyProcessor`

Private helper methods can be tested implicitly through integration tests.

The objective of this ticket is to set up basic configuration to integration tests for `SurveyProcessor`.

# Tasks

- [x] Refactor code to simplify survey processor's instantiation interface
  - Modularize survey parsing and validation steps into a separate function and use this directly inside `SurveyProcessor` class
- [x] Set up configuration under `tests/integration/` folder
- [x] Write some simple integration tests for `SurveyProcessor`
