### ISSUE TITLE
Write unit tests for garbling engine

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#15]
# Description

Write unit tests for the current implementation of the garbling engine, which is important given that garbling is the "meat" of this whole application.

# Tasks

- [x] Add tests for garbling methods (e.g., `garble_block_responses()`)
- [x] Add tests for garbling params
- [x] Ensure no garbling happens inside repeat sections; add relevant tests
