### ISSUE TITLE
Enable submission (i.e., storage) of survey response

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#17]
# Description

Now that DB is set up, enable the app to handle submission and storage of survey response (upon completion).

# Tasks

- [x] Make `SurveyProcessor` handle reaching the survey end
  - Idea: The processor can know it has reached the survey end if its `next()` call results in coming all the way back to the survey root!
- [x] Implement submission-related routing
- [x] Only submit responses to survey elements that have been visited
- [x] On successful storage in DB (make sure to get acknowledgment!), clear out response data from server-side cache
