### ISSUE TITLE
Implement blocked garbling

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#21]
# Description

On Nov 2 (Thu), Sylvain and I met and discussed details of blocked garbling mechanics. We decided to implement an algorithm where:

- Raw responses to blocked garbling questions are encrypted and stored in the database
- These responses are not made available at all for any intermediate download of survey responses
  - Other non-garbled and IID-garbled responses are made available for such intermediate downloads
  - Garbling counts are never made available for intermediate downloads
- These responses are decrypted, garbled altogether, and made available after the survey is finalized and deactivated
  - Garbling counts are made available too at this point

Sylvain expressed that he will be okay with this approach as long as encryption is done properly.

# Tasks

- [x] Design application workflows to handle different garbling schemes
  - IID garbling should happen when each respondent submits their response
  - Blocked garbling should take place when the survey is finalized and deactivated
- [x] Add to `Garbler` functionalities to support Population-Blocked Garbling
- [x] Add to `Garbler` functionalities to support Covariate-Blocked Garbling
