### ISSUE TITLE
Process response data before submission

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#22]
# Description

Raw response data from cache (i.e., server-side session) should be processed before storing it in DB. Specifically, we want to:

1. Encrypt response values for questions subject to Blocked Garbling
2. Garble response values for questions subject to IID Garbling (and update garbling counters as applicable)

# Tasks

- [ ] Encrypt response values for questions subject to Blocked Garbling
  - Increase variance among encrypted values. Potential solutions:
     - Use "salt" (e.g., respondent ID)?
     - Use double encryption (i.e., encrypt whole response object too)?
- [ ] Devise workflows for storing and updating garbling counters
- [ ] Create DB schema for garbling counters
- [ ] Garble response values for questions subject to IID Garbling; and update garbling counters as applicable
