### ISSUE TITLE
Perform custom validation on XLSForm

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#25]
# Description

We want to perform extra validation on the given XLSForm to ensure it meets requirements specific to our application.

# Tasks

- [x] Convert `read_xlsform` to a class with static methods (name it `XLSFormReader`)
- [x] Error out if XSLForm has infinite repeats
  - The application does not support infinite repeats for now. Instead, survey designers can use repeats where the respondent can dynamically set and change the number of repeats. For instance, if the survey has a repeat section asking details of family members (e.g., name, age), it can first ask how many family members the respondent has and then, based on this response, perform repeats.
- [x] Error out if XLSForm has nested repeats
  - The app will NOT support nested repeats (i.e., repeat section within another repeat section); it will only support single-depth repeats. This should be fine given that nested repeats introduce unnecessary complication to administration of the survey itself.
- [x] Error out if XLSForm has unsupported question types
- [x] Error out if XLSForm uses unsupported functions
- [x] Add integration tests
  - Also add test for no garbling in repeat section (validated by `Garbler`)
