### ISSUE TITLE
Streamline survey view

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#26]
# Description

Streamline survey UI.

# Tasks

- [x] Implement form for `note` elements
- [x] Display hint (if provided)
- [x] Raise an error if encountering an unsupported input type
  - NOTE: This check should be done earlier at the initial parsing of XLSForm (during app launch), which is planned to be implemented shortly
  - Update example XLSForm to not raise this error
- [x] Style up survey view
- [x] Create a separate page for response submit
