### ISSUE TITLE
Implement views for different types of questions

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#3]
# Description

Make the app properly render each question type and *cache* responses so they can be used for conditional navigation through the survey.

# Tasks

- [x] Implement controller for language choice
- [x] Implement view for multiple-select questions
- [x] Implement view for single-select questions
- [x] Implement view for text questions
- [x] Implement view for numbers (integer, decimal)
- [x] Implement view for time (date, datetime)
- [x] Display error message
