### ISSUE TITLE
Implement garbling in "mini batches"

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#30]
# Description

Originally, PIs and DDSS planned to encrypt and store true responses and then garble them all when the survey is finalized and deactivated. However, to enhance security and to make the application more distinct from existing ones (e.g., OpenDP), DDSS decided to pursue garbling in "mini batches" (which enables garbling "on the fly" for all schemes) as the main feature rather than an additional feature in the future. In fact, this technique is what had been used and reported in the original study conducted by the PIs, so this shift in development is better justified.

# Tasks

- [x] Modularize schema definitions into `models.py`
- [x] Define schema for `Garbling` table
- [x] Refactor `Garbler` to support garbling in "mini batches"
  - Implement `get_garbler_shock()` method that returns appropriate garbling shock (0 or 1) to be used for the given survey element
- [x] Move submission logic (including DB request) into `Garbler`
  - This makes the route logic lighter
- [x] Manually test the implemented garbling mechanism
