### ISSUE TITLE
Implement covariate-blocked garbling

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#35]
# Description

Augment `Garbler` with logic for covariate-blocked garbling.

# Tasks

- [x] Have submit route check whether the current user is a respondent; and extract their UUID
- [x] Have `Garbler` get respondent UUID and use it to retrieve user covariate values 
- [x] Have `Garbler` make and use covariate block name in its logic
- [x] Make rosters contain no missing data
- [x] Have `Garbler` check if all covariates exist in respondent roster
- [x] Record respondent UUID for each submitted survey response
   - Block re-submission
- [x] Add tests
