### ISSUE TITLE
Set up respondent "login"

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#36]
# Description

Update landing page so that a respondent can identify their role ("Respondent") and use their UUID to "log in", after which they are automatically directed to the survey route.

# Tasks

- [x] Set up user table for authentication
- [x] Set up flask login
- [x] Require authentication for accessing survey routes
- [x] Update landing page with role identification buttons (e.g., "Respondent")
- [x] Create a page for respondent "authentication" (i.e., entering UUID)
