### ISSUE TITLE
Implement translator of XLSForm logic

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#4]
# Description

Implement a method that can translate raw XLSForm formula into the one that Python can evaluate.

# Tasks

- [x] Set up unit testing
- [x] Handle single dot expression (`.`)
- [x] Handle single equal sign (`=`)
- [x] Handle variable expression (e.g., `${name}`)
- [x] Handle custom functions (e.g., `selected-at()`)
