### ISSUE TITLE
Set up enumerator view

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#42]
# Description

Set up enumerator interface where they can:

- View their assigned respondents
- Complete each assigned respondent's survey
- "Rehearse" the survey (without storing response)

# Tasks

- [x] Set up enumerator login
- [x] Set up enumerator view
- [x] Require auth to access enumerator view
- [x] Enable link to complete each respondent's survey
- [x] Record enumerator UUID in survey response (if applicable)
- [x] Record survey completion status on `Respondent` table; make enumerator view reflect this
- [x] Enable link to test/rehearse the survey
