### ISSUE TITLE
Improve admin view

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#44]
# Description

Improve admin interface based on feedback from Lori and Colin on Wednesday 01/17/24.

# Tasks

- [x] Enable click-to-copy on UUIDs
- [x] Enable batch-assigning enumerator
- [x] Enable filtering based on covariates
- [x] Prevent changes to respondent info once their response is submitted
