### ISSUE TITLE
Implement survey exit and logout

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#47]
# Description

Implement buttons that log the user out.

Also, implement a button that lets the user exit the current survey. Specifically, the exit button, when clicked, will:

1. Prompt a warning that current survey data will not be stored
2. If "yes", clear survey data and redirect to index page
  a. If real survey session, perform logout too

# Tasks

- [x] Add logout button to admin view
- [x] Add logout button to enumerator view
- [x] Refactor `SurveySession.clear()` to delete data in its scope only
  - That is, do NOT delete the entire session because it may be used by other components (e.g., authentication)
- [x] Implement survey exit route and button
- [x] Clear survey data upon submit in testing mode
