### ISSUE TITLE
Implement survey deactivation

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#56]
# Description

We want admin to be able to deactivate and reactivate the survey for maintenance as well as for termination. When the survey is deactivated, the app should:

1. Display the message
2. Disable access by respondents or enumerators

Note that we want a solution that can set sync this global state across all its instances.

# Tasks

- [x] Define schema for a table to store the application's global states
- [x] Initialize application's global states on launch, including activation
- [x] Restrict access under survey deactivation
  - Respondents cannot access survey at all
  - Enumerators can access their interface but cannot run survey on behalf of their assigned respondents
  - Admin can access their interface with all functionalities intact
  - Admin can reactivate the survey
- [x] Create button and route for survey de/re-activation
