### ISSUE TITLE
Perform miscellaneous refactors

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#60]
# Description

Perform miscellaneous refactors to make code easier to read and maintain. None of these changes alters application behavior.

# Tasks

- [x] Use `context_processor` to inject template variables
- [x] Move instantiation of `SurveySession` into `SurveyProcessor`
- [x] Embed garbling info into the metadata of the survey form
- [x] Split `before_request` decorator into two for clarity on actions performed
