### ISSUE TITLE
Streamline app creation

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#61]
# Description

Current setup for app creation is verbose, clumsy, and scattered. We want to improve it by 1) locating all app-level setup logic in the app factory (i.e., `create_app()`) and 2) modularizing heavy logic into other functions.

# Tasks

- [x] Move login manager setup to auth folder
- [x] Move admin setup to auth folder
- [x] Move app-level decorator logic into app factory
