### ISSUE TITLE
Set up custom error handling

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#65]
# Description

Currently, the application breaks when errors are raised. This is not ideal for user experience, so we want to create and use a custom error handler that:

- Uses Flask's default error handler if the application is in debug mode
- Otherwise simply flashes error message without crashing the application

# Tasks

- [x] Set up default (app-level) error handler
  - Use Flask's default error handler if the application is in debug mode
  - Otherwise simply flash error message without crashing the application
- [x] Custom handle `StaleDataError` in survey blueprint
  - Flash: "Sorry, we missed your submission. Please try again in a bit."
- [x] Custom handle `IntegrityError` in survey blueprint
  - Flash: "Response had already been submitted."
