### ISSUE TITLE
Add logging

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#67]
# Description

Set up and use logging to monitor major events

# Tasks

- [x] Configure flask logger
- [x] Log auth routes
- [x] Log survey routes
- [x] Log admin routes
