### ISSUE TITLE
Implement survey termination

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#71]
# Description

We want to differentiate between survey termination from temporary survey deactivation.

Specifically, we want the following to happen on survey termination:

1. Garbling table is dropped
2. Only admin can access the survey
3. Admin cannot activate the survey again

To take caution on this irreversible action, use an interstitial page for confirmation where admin should re-enter their credentials.

# Tasks

- [x] Rename "deactivation" to "pause"
- [x] Set the survey to pause by default when initially launched
- [x] Implement survey termination
- [x] Add an interstitial page for reconfirming survey termination
- [x] Rename `SurveyStatus` to `ResponseStatus`
