### ISSUE TITLE
Enhance code quality

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#73]
# Description

Make non-breaking changes that make the code easier to read and maintain.

# Tasks

- [x] Use `@classmethod` instead of `@staticmethod` if methods interact with one another within the same class
- [x] Rename `SurveyProcessorBase` to `XLSFormFunctions`
  - To avoid potential confusion and misuse around `SurveyProcessorBase`
- [x] Remove `methods=["GET", "POST"]` from enumerator route
  - Outdated code
- [x] Sort records by ID in SurveyResponse.to_csv_string()
  - Order matters for garbling inference (add documentation about this too)
- [x] Reorganize `models.py` module
