### ISSUE TITLE
Add project documentation

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#80]
# Description

Add contents to MkDocs.

# Tasks

- [x] Create `Home` page
- [x] Create `Quickstart` page
- [x] Create `Deploying App` page
- [x] Create `Creating Survey Files` page
- [x] Create `Garbling` page under `Concepts` section
- [x] Set up `Analyzing Results` page
  - Contents to be contributed by PIs
- [x] Create `Getting Help` page
- [x] Set up `Contributing` page
  - Contents to be fleshed out later
- [x] Update README
- [x] Create contents for the `Contributing` guide
- [ ] Gather and integrate feedback on drafts
  - [x] Make `Contributing` a separate section outside `Guides`
  - [ ] Commit original paper's PDF to repo; and link to it
  - [ ] Make the citation of the foundation paper more prominent upfront in both `Home` and `Quickstart` pages
  - [ ] Fully explain technical details of garbling in the concepts page but as an expandable/collapsible box
  - [ ] Make the link to the example XLSForm more prominent (as an admonition box)
  - [ ] Clarify upfront that the application is NOT about identifying cases that need following up

**Comment by yoonspark** [comment]
Feedback from Eric:

> I enjoyed seeing your work on this! A few comments:
>
> 1. If the main target audience is academics, I would put a citation and link to the paper that introduces the method front and center on the first page.
> 2. Same again with the quickstart guide.
> 3. You could probably get more technical on the garbling explainer page. Once the site is built out a bit more, if this looks like similar sites I’ve seen, I should probably (?) be able to fully understand the technical details just by reading the website.
> 4. Make the link to the example XLSForm more prominent
> 5. Contributing tab looks great
> 6. Might be worth mentioning more about what this is NOT. For example, my impression is that this is NOT designed to help, say, HR identify cases that need following up. Instead it’s just designed to yield valid population mean estimates.

Plus, he suggested giving more concrete/specific guide on parameter values (e.g., "X is a good garbling rate if your survey has Y number of respondents").

**Comment by yoonspark** [comment]
Feedback from Joel:

> Documentation website questions and comments:
> - Overall, this looks fantastic. You have a lot of content here already and the site is snappy. 
> - The YouTube demo video is great to have here.
>     - I noticed the video is currently unlisted, which makes sense. Will it eventually be listed?
>     - Are you comfortable with the video being associated with your personal YouTube channel?
> - The search bar is excellent – fast and with preview results.
> - I like the MkDocs approach. It’s good that the documentation website itself is part of the application’s git repo. 
>     - I am curious if the static site immediately and automatically reflects changes in the repo?
> - Links that leave the website could open to a new window:
>     - Home page link to repo (in the top right corner)
>     - Link to installing Docker from Quickstart page
>     - Link to the paper at bottom of Garbling page
>     - Link to Stats4SD on bottom of Creating Survey Files page.
>     - Link to discussions on the Getting Help page.
> - Apart from linking to the DDSS GitHub repo, do you want to link to https://ddss.princeton.edu/ somewhere (or otherwise advertise the DDSS)?
> 
> Other questions:
> - It seems unavoidable that, in the end, the user must trust that the application is doing what it says it is doing (whether it is an anonymized or garbled survey or e2e encrypted messaging service or something else). Open sourcing the code can help mollify concerns, but there’s always the possibility of bugs. What else can be done to minimize the amount of trust required from the user? Perhaps publishing results of application testing? Third-party testing? 
> - This might be a bad idea, but, can the garbling strategy (e.g., block vs IID) change dynamically as a function of the number of survey respondents?

**Comment by yoonspark** [comment]
Closed this for a formal wrap-up of the project.
