### ISSUE TITLE
Implement IID Garbling

### ISSUE THREAD

**Issue by yoonspark** [princeton-ddss/safely-report#9]
# Description

With the following definition of a garbled report (which appears on page 15 of the PIs' [paper](https://www.nber.org/system/files/working_papers/w31011/w31011.pdf)):

r̃<sub>i,a</sub> = r<sub>i,a</sub> + (1 - r<sub>i,a</sub>)⋅η<sub>i,a</sub>

Implement a garbling engine that supports the following algorithm:

1. At each report, generate a new Bernoulli random value with the probability of π
2. Use this value in place of η<sub>i,a</sub> in the definition above to produce the garbled result

# Tasks

- [x] Devise how to specify garbling parameters in XLSForm
- [x] Build a garbling engine that can parse, validate, and cache these parameters
- [x] Equip the garbling engine with the capacity to inject noise according to the algorithm above
